import './global.css';

export const metadata = {
  title: 'Welcome to bank',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className="overflow-hidden mx-auto max-w-7xl px-6 lg:px-8 py-8">
        {children}
      </body>
    </html>
  );
}
